version: '3.3'
services:
    lhcr1_keycloak:
        ports:
            - '${LHCR1_KEYCLOAK_PORT}:8080'
        environment:
            - KEYCLOAK_USER=${LHCR1_KEYCLOAK_USER}
            - KEYCLOAK_PASSWORD=${LHCR1_KEYCLOAK_PW}
            - KEYCLOAK_IMPORT=/tmp/lhcrrealm.json
            - KEYCLOAK_FRONTEND_URL=http://lhcr1:8081/auth/
            
        volumes:
            - ./configs/lhcr1/keycloak-export.json:/tmp/lhcrrealm.json
        command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.token_exchange=enabled", "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"]
        image: jboss/keycloak${KEYCLOAK_TAG}
        networks: 
            - lhcr1
        extra_hosts:
            - lhcr2:${IP}
            - lhcr1:${IP}

    lhcr1_kong-db:
        image: postgres${KONG_DB_TAG}
        ports:
            - ${LHCR1_KONG_DB_PORT}:5432
        environment:
            POSTGRES_USER:     ${LHCR1_KONG_DB_USER}
            POSTGRES_PASSWORD: ${LHCR1_KONG_DB_PW}
            POSTGRES_DB:       ${LHCR1_KONG_DB_NAME}
        networks: 
            - lhcr1
        extra_hosts:
            - lhcr2:${IP}
            - lhcr1:${IP}

    lhcr1_kong:
        image: lhcr/kong-oidc
        ports:
            - ${LHCR1_KONG_PORT}:8000
            - ${LHCR1_KONG_SECURE_PORT}:8443
            - ${LHCR1_KONG_ADMIN_PORT}:8001
            - ${LHCR1_KONG_SECURE_ADMIN_PORT}:8444
        environment:
            KONG_DATABASE:    postgres
            KONG_PG_HOST:     lhcr1_kong-db
            KONG_PG_DATABASE: ${LHCR1_KONG_DB_NAME}
            KONG_PG_USER:     ${LHCR1_KONG_DB_USER}
            KONG_PG_PASSWORD: ${LHCR1_KONG_DB_PW}
            KONG_ADMIN_LISTEN: 0.0.0.0:${LHCR1_KONG_HTTP_ADMIN_PORT}
            KONG_PROXY_LISTEN: 0.0.0.0:${LHCR1_KONG_HTTP_PROXY_PORT}
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG:  /dev/stderr
            KONG_ADMIN_ERROR_LOG:  /dev/stderr
            KONG_PLUGINS: bundled,oidc
        volumes:
            - ./configs/lhcr1/kong.yml:/tmp/kong.yml
        networks: 
            - lhcr1
        extra_hosts:
            - lhcr2:${IP}
            - lhcr1:${IP}
        depends_on:
            - lhcr1_kong-db

networks:
    lhcr1:
