version: '3.3'
services:
    lhcr2-keycloak:
        ports:
            - '${LHCR2_KEYCLOAK_PORT}:8080'
        environment:
            - KEYCLOAK_USER=${LHCR2_KEYCLOAK_USER}
            - KEYCLOAK_PASSWORD=${LHCR2_KEYCLOAK_PW}
            - KEYCLOAK_IMPORT=/tmp/lhcrrealm.json
            - KEYCLOAK_FRONTEND_URL=http://lhcr2:8082/auth/
        volumes:
            - ./configs/lhcr2/keycloak-export.json:/tmp/lhcrrealm.json
        command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.token_exchange=enabled", "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"]
        image: jboss/keycloak${KEYCLOAK_TAG}
        networks: 
            - lhcr2
        extra_hosts:
            - lhcr2:${IP}
            - lhcr1:${IP}
    
    lhcr2-kong-db:
        image: postgres${KONG_DB_TAG}
        ports:
            - ${LHCR2_KONG_DB_PORT}:5432
        environment:
            POSTGRES_USER:     ${LHCR2_KONG_DB_USER}
            POSTGRES_PASSWORD: ${LHCR2_KONG_DB_PW}
            POSTGRES_DB:       ${LHCR2_KONG_DB_NAME}
        networks: 
            - lhcr2
        extra_hosts:
            - lhcr2:${IP}
            - lhcr1:${IP}
    
    lhcr2-kong:
        image: lhcr/kong-oidc
        ports:
            - ${LHCR2_KONG_PORT}:8000
            - ${LHCR2_KONG_SECURE_PORT}:8443
            - ${LHCR2_KONG_ADMIN_PORT}:8001
            - ${LHCR2_KONG_SECURE_ADMIN_PORT}:8444
        environment:
            KONG_DATABASE:    postgres
            KONG_PG_HOST:     lhcr2-kong-db
            KONG_PG_DATABASE: ${LHCR2_KONG_DB_NAME}
            KONG_PG_USER:     ${LHCR2_KONG_DB_USER}
            KONG_PG_PASSWORD: ${LHCR2_KONG_DB_PW}
            KONG_ADMIN_LISTEN: 0.0.0.0:${LHCR2_KONG_HTTP_ADMIN_PORT}
            KONG_PROXY_LISTEN: 0.0.0.0:${LHCR2_KONG_HTTP_PROXY_PORT}
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG:  /dev/stderr
            KONG_ADMIN_ERROR_LOG:  /dev/stderr
            KONG_PLUGINS: bundled,oidc
        volumes:
            - ./configs/lhcr2/kong.yml:/tmp/kong.yml
        networks: 
            - lhcr2
        extra_hosts:
            - lhcr2:${IP}
            - lhcr1:${IP}
        depends_on:
            - lhcr2-kong-db
    lhcr2-fhirserver:
        image: elementech/fhirjpa
        build:
            context: ./jpa_fhir_server
            dockerfile: Dockerfile
        volumes:
            - ./configs/lhcr2/hapi.properties.server:/tmp/hapi.properties
        environment:
            - "JAVA_OPTS=-Dhapi.properties=/tmp/hapi.properties"
        networks: 
            - lhcr2
        extra_hosts:
            - lhcr2:${IP}
            - lhcr1:${IP}
        
        
networks:
    lhcr2:
