_format_version: '1.1'
services:
- host: 192.168.128.11
  created_at: 1593358423
  connect_timeout: 60000
  id: 3a400851-a303-492d-aca4-70ff1261f5f1
  protocol: https
  name: Spine-MESHAPI
  read_timeout: 60000
  port: 443
  path: /messageexchange
  updated_at: 1593371958
  retries: 5
  write_timeout: 60000
  tags: {}
- host: 192.168.128.11
  created_at: 1593357618
  connect_timeout: 60000
  id: 51663c3a-64f1-4103-bdf5-1cba0d754c1a
  protocol: https
  name: Spine-NEMS
  read_timeout: 60000
  port: 443
  path: /STU3
  updated_at: 1593371958
  retries: 5
  write_timeout: 60000
  tags: {}
- host: 192.168.128.11
  created_at: 1593358634
  connect_timeout: 60000
  id: 7d6edc47-d03b-4a9d-8f1a-99cdf873fdfe
  protocol: https
  name: Spine-SMSP
  read_timeout: 60000
  port: 443
  path: /smsp/pds
  updated_at: 1593371958
  retries: 5
  write_timeout: 60000
  tags: {}
- host: 192.168.128.16
  created_at: 1593372188
  connect_timeout: 60000
  id: 7f3c8700-75d0-4e3c-b970-0bf1e34bffc7
  protocol: https
  name: Spine-GPConnect1.x
  read_timeout: 60000
  port: 19192
  path: /v1/fhir
  updated_at: 1593372188
  retries: 5
  write_timeout: 60000
  tags: {}
- host: 192.168.128.16
  created_at: 1593372051
  connect_timeout: 60000
  id: 9d0727f6-062b-4999-8b57-ea527f471a4a
  protocol: https
  name: Spine-GPConnect0.x
  read_timeout: 60000
  port: 19192
  path: /v0/fhir
  updated_at: 1593372051
  retries: 5
  write_timeout: 60000
  tags: {}
- host: lhcr1-fhirserver
  created_at: 1578871225
  connect_timeout: 60000
  id: fe8e5ce1-c0a5-4712-b07d-56e996694a8c
  protocol: http
  name: HapiJPA
  read_timeout: 60000
  port: 8080
  path: /hapi-fhir-jpaserver/fhir/
  updated_at: 1593371958
  retries: 5
  write_timeout: 60000
routes:
- id: 020bc150-2d4f-49aa-8e4d-9f61b63eda38
  updated_at: 1593372124
  protocols:
  - http
  - https
  created_at: 1593372124
  service: 9d0727f6-062b-4999-8b57-ea527f471a4a
  name: GPConnect0.x
  preserve_host: false
  regex_priority: 0
  strip_path: true
  paths:
  - /gpconnect0
  https_redirect_status_code: 426
- id: 11ee447a-2445-474d-a05c-0de179f34de2
  updated_at: 1593371958
  protocols:
  - http
  - https
  created_at: 1593358455
  service: 3a400851-a303-492d-aca4-70ff1261f5f1
  name: MESHAPI
  preserve_host: false
  regex_priority: 0
  strip_path: true
  paths:
  - /meshapi
  https_redirect_status_code: 426
- id: 285760ae-08fd-4814-b5cd-cb3e28ba86a1
  updated_at: 1593371958
  protocols:
  - http
  - https
  created_at: 1591448854
  service: fe8e5ce1-c0a5-4712-b07d-56e996694a8c
  name: metadata
  preserve_host: false
  regex_priority: 0
  strip_path: true
  paths:
  - /fhir/metadata
  https_redirect_status_code: 426
- id: a4145fb2-42f1-4c77-98aa-0810dea8784f
  updated_at: 1593372797
  protocols:
  - http
  - https
  created_at: 1593358651
  service: 7d6edc47-d03b-4a9d-8f1a-99cdf873fdfe
  name: SpineSMSP
  preserve_host: false
  regex_priority: 0
  strip_path: true
  paths:
  - /smsp
  https_redirect_status_code: 426
  hosts: {}
  methods: {}
- id: a4726cab-f489-40ec-b83d-10f52a96998a
  updated_at: 1593371958
  protocols:
  - http
  - https
  created_at: 1578871242
  service: fe8e5ce1-c0a5-4712-b07d-56e996694a8c
  name: fhir
  preserve_host: false
  regex_priority: 0
  strip_path: true
  paths:
  - /fhir
  https_redirect_status_code: 426
- id: a4808204-6caf-470e-93f6-90f5c196679d
  updated_at: 1593371958
  protocols:
  - http
  - https
  created_at: 1593357638
  service: 51663c3a-64f1-4103-bdf5-1cba0d754c1a
  name: NEMS
  preserve_host: false
  regex_priority: 0
  strip_path: true
  paths:
  - /nems
  https_redirect_status_code: 426
  hosts: {}
  methods: {}
- id: bff3c58d-deec-4971-9553-8f1735ae6c3d
  updated_at: 1593372781
  protocols:
  - http
  - https
  created_at: 1593372221
  service: 7f3c8700-75d0-4e3c-b970-0bf1e34bffc7
  name: GPConnect1.x
  preserve_host: false
  regex_priority: 0
  strip_path: true
  paths:
  - /gpconnect1
  https_redirect_status_code: 426
  hosts: {}
  methods: {}
plugins:
- created_at: 1578871686
  config:
    response_type: code
    introspection_endpoint: http://lhcr1:8081/auth/realms/lhcr1/protocol/openid-connect/token/introspect
    bearer_only: 'no'
    ssl_verify: 'no'
    introspection_endpoint_auth_method: client_secret_post
    realm: kong
    redirect_after_logout_uri: /
    scope: openid
    token_endpoint_auth_method: client_secret_post
    client_secret: 0efb256c-cdb9-439b-9767-c6b997a4e827
    client_id: kong
    logout_path: /fhir/logout
    discovery: http://lhcr1:8081/auth/realms/lhcr1/.well-known/openid-configuration
  id: 11156427-b8b5-414b-95a1-baabcaef459b
  name: oidc
  protocols:
  - grpc
  - grpcs
  - http
  - https
  enabled: true
  run_on: first
  route: a4726cab-f489-40ec-b83d-10f52a96998a
- created_at: 1591450192
  config:
    remove:
      querystring: {}
      headers: {}
      body: {}
    replace:
      querystring: {}
      headers: {}
      uri: /hapi-fhir-jpaserver/fhir/metadata
      body: {}
    add:
      querystring: {}
      headers: {}
      body: {}
    append:
      querystring: {}
      headers: {}
      body: {}
    rename:
      querystring: {}
      headers: {}
      body: {}
  id: 135c9ee6-bb20-45e7-a2dd-ec0eb55119fa
  name: request-transformer
  protocols:
  - grpc
  - grpcs
  - http
  - https
  enabled: true
  run_on: first
  route: 285760ae-08fd-4814-b5cd-cb3e28ba86a1
